apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    role: cache
  name: todo-cache
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      role: cache-instance
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: cache-instance
    spec:
      containers:
      - name: redis-cache
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-cache-service
  labels:
    role: cache-service
  namespace: default
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    role: cache-instance
  type: NodePort
