apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    role: s3
  name: todo-s3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      role: s3-instance
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: s3-instance
    spec:
      containers:
      - name: minio-s3
        image: minio/minio:RELEASE.2018-06-09T03-43-35Z
        args: ["server", "/data"]
        ports:
        - containerPort: 9000
        env:
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: secret-key
        volumeMounts:
        - name: s3-data
          mountPath: "/data"
        - name: s3-config-data
          mountPath: "/root/.minio"
      volumes:
        - name: s3-data
          persistentVolumeClaim:
            claimName: minio-pv-claim
        - name: s3-config-data
          hostPath:
            path: "/home/docker/s3-config-data"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-s3-service
  labels:
    role: s3-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 9000
  selector:
    role: s3-instance
  type: NodePort

